<?php
namespace App\Services;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;
use RuntimeException;
class AiEmployeeService {
 public function run(string $taskType,string $requirement):array { $start=microtime(true); $demo=(bool)config('ai_employee.demo_mode')||blank(config('ai_employee.api_key')); if($demo){$out=$this->demoOutput($taskType,$requirement);return ['output'=>$out,'mode'=>'demo','duration_ms'=>(int)((microtime(true)-$start)*1000)];} $out=$this->callOpenAI($taskType,$requirement); return ['output'=>$out,'mode'=>'live','duration_ms'=>(int)((microtime(true)-$start)*1000)]; }
 private function callOpenAI(string $taskType,string $requirement):string { $system="You are DevPilot AI, a senior Laravel 12 + Vue 3 + Inertia.js web-development employee. Return practical implementation-ready output. Never claim code was tested unless it was actually tested. Use sections such as Objective, Assumptions, Analysis, Architecture, Database, API, Frontend, Implementation, Edge Cases, Security, Testing and Verification when relevant. Be explicit about file paths. Task type: {$taskType}"; $response=Http::timeout(config('ai_employee.timeout'))->withToken(config('ai_employee.api_key'))->acceptJson()->post(config('ai_employee.base_url').'/responses',['model'=>config('ai_employee.model'),'input'=>[['role'=>'system','content'=>$system],['role'=>'user','content'=>$requirement]]]); if($response->failed()) throw new RuntimeException('AI provider error: '.$response->status().' '.$response->body()); $json=$response->json(); $text=$json['output_text']??null; if(!$text&&isset($json['output'])){foreach($json['output'] as $item){foreach(($item['content']??[]) as $content){if(isset($content['text']))$text=($text?"{$text}\n":'').$content['text'];}}} if(blank($text))throw new RuntimeException('AI provider returned no text output.'); return $text; }
 private function demoOutput(string $taskType,string $requirement):string { $clean=Str::limit(trim(preg_replace('/\s+/',' ',$requirement)),260); $title=match($taskType){'requirement'=>'Requirement Analysis','database'=>'Database Schema Plan','api'=>'API Plan','bug'=>'Bug Analysis','vue'=>'Vue Component Plan','crud'=>'Laravel CRUD Plan','documentation'=>'Technical Documentation Plan','testing'=>'Testing Checklist',default=>'Development Analysis'}; return "# {$title}\n\n> **Demo mode:** Generated locally so the complete workflow can be tested without an API key.\n\n## Requirement\n{$clean}\n\n## Objective\nConvert this requirement into an implementation-ready Laravel 12 + Vue 3 + Inertia.js plan.\n\n## Assumptions\n- Laravel 12 backend.\n- Vue 3 + Inertia.js frontend.\n- SQLite or MySQL database.\n- Protected actions require authentication and authorization.\n\n## Recommended Architecture\n- Controller coordinates validated requests.\n- Form Request owns validation rules.\n- Models own relationships and persistence concerns.\n- Services hold reusable business logic when complexity grows.\n- Vue pages orchestrate screens; reusable components handle forms, tables, filters and states.\n\n## Development Tasks\n1. Confirm requirements and edge cases.\n2. Create migrations and relationships.\n3. Create models, requests, controllers and routes.\n4. Build reusable Vue components.\n5. Connect frontend actions to the backend.\n6. Add validation and authorization.\n7. Test success and failure paths.\n8. Document the final implementation.\n\n## Edge Cases\n- Missing or invalid input\n- Duplicate records\n- Unauthorized actions\n- Record not found\n- Empty results\n- Network/API failure\n- Concurrent updates\n\n## Human Verification\n- Verify every assumption against the real project.\n- Run migrations against the actual database.\n- Execute generated code.\n- Test browser and API behavior.\n- Review security, authorization and edge cases.\n\n## Next Step\nUse the output as a draft, then verify and adapt it to the actual codebase before production use."; }
}
